;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        end-of-buffer
        indent-for-tab-command
        kill-region
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-kill
        smex
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-set-region
        ))
